# Generated by Django 5.2 on 2025-05-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_time',
            field=models.CharField(max_length=100),
        ),
    ]
