# Generated by Django 5.2 on 2025-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_alter_chatmessage_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
