# Generated by Django 5.1.4 on 2025-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_alter_chatmessage_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='is_personal_chat',
            field=models.BooleanField(default=False),
        ),
    ]
